### ISSUE TITLE
Fontsize for code in rendered README is for ants

### ISSUE THREAD

**Issue by fredrikekre** [JuliaComputing/JuliaHub#13]
I suggest getting rid of
```css
.readme code {
	font-size: 85%;
}
```
